In [17]:
#coding:utf-8
import pandas as pd
from sklearn.metrics import mean_squared_error
# 题目要求是预测5个品牌的上牌量，所以对数据进行重构操作
# 针对初赛的数据重构
#
train = pd.read_csv('data/train_20171215.txt',sep='\t')
an = pd.read_csv('data/answer_A_20180225.txt',sep='\t',header=None)
an.rename(columns={0:'date',1:'cnt'},inplace=True)
# print an
# exit()
new_train = pd.DataFrame()
new_data = []
brand = []
for i in range(1032):
    for j in range(5):
        new_data.append(i+1)
        brand.append(j+1)

day_of_week = train.groupby('date',as_index=False).day_of_week.mean()
new_train['date'] = list(new_data)
new_train['brand'] = list(brand)

train = pd.merge(new_train,train,on=['date','brand'],how='left')
del train['day_of_week']
train = pd.merge(train,day_of_week,on=['date'],how='left')
train['cnt'] = train['cnt'].fillna(0)

##########################################################
test = pd.read_csv('data/test_B_20171225.txt',sep='\t')
print(test)

new_test = pd.DataFrame()
new_data_ = []
brand_ = []
test_len = 1307 - 1032 + 1

print('预测天数:',test_len)

for i in range(test_len):
    for j in range(5):
        new_data_.append(i+1308)
        brand_.append(j+1)

new_test['date'] = list(new_data_)
new_test['brand'] = list(brand_)

test = pd.merge(new_test,test,on=['date'],how='left')


##########################################################
train = train.copy()
test = test.copy()

val_data = train[train['date'] > 1032 - test_len]
test['cnt'] = 1111
val_data = test


to_sub_val_data = val_data.copy()
print ('val_date',1032 - 757 + 1)

train_data = train[(train['date'] <= 1032 - test_len) & (train['date'] > 480)]

print (len(train_data.date.unique()))


history_rule_mean = train_data.groupby(['brand','day_of_week'],as_index=False).cnt.mean()
history_rule_median = train_data.groupby(['brand','day_of_week'],as_index=False).cnt.median()
history_rule = train_data.groupby(['brand'],as_index=False).cnt.mean()
day_of_week_rule = train_data.groupby(['day_of_week'],as_index=False).cnt.mean()

history_rule_mean.rename(columns={'cnt':'h_mean_cnt'},inplace=True)
history_rule_median.rename(columns={'cnt':'h_median_cnt'},inplace=True)
history_rule.rename(columns={'cnt':'h_brand_cnt'},inplace=True)
day_of_week_rule.rename(columns={'cnt':'h_day_of_week_cnt'},inplace=True)

val_data = pd.merge(val_data,history_rule_median,on=['brand','day_of_week'])
val_data = pd.merge(val_data,history_rule_mean,on=['brand','day_of_week'])
val_data = pd.merge(val_data,history_rule,on=['brand'])
val_data = pd.merge(val_data,day_of_week_rule,on=['day_of_week'])


# val_data = val_data[val_data['cnt']!=0]

tmp = val_data.groupby(['date'],as_index=False)['cnt','h_mean_cnt','h_median_cnt','h_brand_cnt','h_day_of_week_cnt'].sum()
val_data = pd.merge(val_data[['date']],tmp,on=['date'])
# print val_data

# print mean_squared_error(val_data['cnt'],val_data['h_mean_cnt'] * 0.95 + val_data['h_median_cnt'] * 0.05)
# print mean_squared_error(val_data['cnt'],val_data['h_mean_cnt'] * 1.1)
# print mean_squared_error(val_data['cnt'],val_data['h_brand_cnt'])
# print mean_squared_error(val_data['cnt'],val_data['h_median_cnt'])
# print mean_squared_error(val_data['cnt'],val_data['h_day_of_week_cnt'])
#
# print mean_squared_error(val_data['cnt'],val_data['h_day_of_week_cnt'] * 1.1)
#
# print mean_squared_error(val_data['cnt'],val_data['h_day_of_week_cnt'] * 0.5 + val_data['h_mean_cnt'] * 0.5)
#


val_data = pd.merge(val_data,to_sub_val_data,on=['date'])


val_data = val_data[['date','h_mean_cnt','day_of_week','h_day_of_week_cnt']]
val_data = pd.DataFrame(val_data).drop_duplicates(['date'])
val_data = val_data.sort_values(['date'])
import numpy as np

val_data.loc[val_data['day_of_week']<=5,'cnt'] = val_data.loc[val_data['day_of_week']<=5,'h_day_of_week_cnt'] * 1.1
val_data.loc[val_data['day_of_week']>6,'cnt'] = val_data.loc[val_data['day_of_week']>6,'h_day_of_week_cnt'] * 0.5
val_data.loc[val_data['day_of_week']==6,'cnt'] = val_data.loc[val_data['day_of_week']==6,'h_day_of_week_cnt'] * 1.75

val_data[['date','cnt']].to_csv('data/20180226.txt',index=False,header=False,sep='\t')
print (val_data[['date','cnt']])

ind = []
res = []

for i,data in enumerate(val_data[['date','cnt','day_of_week']].values):
    if i % 4 == 0:
        if data[2] == 7:
            # data[1] * 0.7
            ind.append(data[0])
            res.append(data[1] * 0.5)
        else:
            ind.append(data[0])
            res.append(data[1])
    else:
        ind.append(data[0])
        res.append(data[1])

print('hahahah',res)

val_data = pd.DataFrame()
val_data['date'] = list(ind)
val_data['cnt'] = list(res)
val_data['date'] = val_data['date'].astype(int)
# val_data['cnt'] = val_data['cnt'] - 1
val_data[['date','cnt']].to_csv('data/20180226.txt',index=False,header=False,sep='\t')
#
# answer = pd.read_csv('../data/answer_A_20180225.txt',sep='\t',header=None)
# answer.rename(columns={0:'date',1:'t_cnt'},inplace=True)
#
# #
# anl = pd.merge(val_data[['date','cnt']],answer,on=['date'])
# # anl.loc[anl['date']==1032,'cnt'] = 600
# # print anl
# print mean_squared_error(anl['t_cnt'],anl['cnt'])
#
# print anl

     date  day_of_week
0    1308            5
1    1309            6
2    1310            7
3    1311            1
4    1312            2
5    1313            3
6    1314            4
7    1315            5
8    1316            6
9    1317            1
10   1318            2
11   1319            3
12   1320            4
13   1321            5
14   1322            6
15   1323            1
16   1324            2
17   1325            3
18   1326            4
19   1327            5
20   1328            6
21   1329            1
22   1330            2
23   1331            3
24   1332            4
25   1333            5
26   1334            6
27   1335            7
28   1336            1
29   1337            2
..    ...          ...
242  1550            1
243  1551            2
244  1552            3
245  1553            4
246  1554            5
247  1555            6
248  1556            7
249  1557            1
250  1558            2
251  1559            3
252  1560            4
253  1561            5
254  1562            6
255  1563            7
256  1564            1
257  1565            2
258  1566            3
259  1567            4
260  1568            5
261  1569            6
262  1570            7
263  1571            1
264  1572            2
265  1573            3
266  1574            4
267  1575            5
268  1576            6
269  1577            7
270  1578            1
271  1579            2

[272 rows x 2 columns]
预测天数: 276
val_date 276
276
      date          cnt
0     1308  2137.625000
1025  1309   662.958333
2025  1310   557.850000
2850  1311  2685.975000
3800  1312  2758.393478
4800  1313  2355.906667
5800  1314  1930.402222
25    1315  2137.625000
1050  1316   662.958333
2875  1317  2685.975000
3825  1318  2758.393478
4825  1319  2355.906667
5825  1320  1930.402222
50    1321  2137.625000
1075  1322   662.958333
2900  1323  2685.975000
3850  1324  2758.393478
4850  1325  2355.906667
5850  1326  1930.402222
75    1327  2137.625000
1100  1328   662.958333
2925  1329  2685.975000
3875  1330  2758.393478
4875  1331  2355.906667
5875  1332  1930.402222
100   1333  2137.625000
1125  1334   662.958333
2050  1335   557.850000
2950  1336  2685.975000
3900  1337  2758.393478
...    ...          ...
3675  1550  2685.975000
4675  1551  2758.393478
5700  1552  2355.906667
6700  1553  1930.402222
925   1554  2137.625000
1925  1555   662.958333
2750  1556   557.850000
3700  1557  2685.975000
4700  1558  2758.393478
5725  1559  2355.906667
6725  1560  1930.402222
950   1561  2137.625000
1950  1562   662.958333
2775  1563   557.850000
3725  1564  2685.975000
4725  1565  2758.393478
5750  1566  2355.906667
6750  1567  1930.402222
975   1568  2137.625000
1975  1569   662.958333
2800  1570   557.850000
3750  1571  2685.975000
4750  1572  2758.393478
5775  1573  2355.906667
6775  1574  1930.402222
1000  1575  2137.625000
2000  1576   662.958333
2825  1577   557.850000
3775  1578  2685.975000
4775  1579  2758.393478

[272 rows x 2 columns]